### ISSUE TITLE
gemify?

### ISSUE THREAD

**Issue by jronallo** [shell/rails3_before_render#2]
With plugins deprecated is there any plans or interest in turning this into a gem?

**Comment by shell** [comment]
yes I can do that. Thanks for notice. Do you find this plugin useful?

**Comment by jronallo** [comment]
Yes, I've found it very useful. Thank you! I use it along with a Rails Engine gem which provides controllers. It means I don't have to override controller methods in my own application. Instead, I can use before_render to query an API, add some variables, or do other calculations based on what the Engine controller returns for a custom view.

**Comment by shell** [comment]
closed with #3

**Comment by jronallo** [comment]
Just wanted to let you know that I've been using the gem now for a few weeks and it is working well. Thank you so much for turning this into a gem.
